// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HW.Models
{
    public partial class CourseInstructor
    {
        [Key]
        public int CourseID { get; set; }
        [Key]
        public int InstructorID { get; set; }

        [ForeignKey(nameof(CourseID))]
        [InverseProperty("CourseInstructor")]
        public virtual Course Course { get; set; }
        [ForeignKey(nameof(InstructorID))]
        [InverseProperty(nameof(Person.CourseInstructor))]
        public virtual Person Instructor { get; set; }
    }
}