// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HW.Models
{
    public partial class Department
    {
        public Department()
        {
            Course = new HashSet<Course>();
        }

        [Key]
        public int DepartmentID { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        [Column(TypeName = "money")]
        public decimal Budget { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StartDate { get; set; }
        public int? InstructorID { get; set; }
        [Required]
        public byte[] RowVersion { get; set; }

        public bool IsDeleted { get; set; }

        public DateTime? DateModified { get; set; }

        [ForeignKey(nameof(InstructorID))]
        [InverseProperty(nameof(Person.Department))]
        public virtual Person Instructor { get; set; }
        [InverseProperty("Department")]
        public virtual ICollection<Course> Course { get; set; }
    }
}