// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HW.Models
{
    public partial class vwCourseStudents
    {
        public int? DepartmentID { get; set; }
        [StringLength(50)]
        public string DepartmentName { get; set; }
        public int CourseID { get; set; }
        [StringLength(50)]
        public string CourseTitle { get; set; }
        public int? StudentID { get; set; }
        [StringLength(101)]
        public string StudentName { get; set; }
    }
}