// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HW.Models
{
    public partial class vwCourseStudentCount
    {
        public int? DepartmentID { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        public int CourseID { get; set; }
        [StringLength(50)]
        public string Title { get; set; }
        public int? StudentCount { get; set; }
    }
}